version: '3'

networks:
  arpm-php-object-network:

services:

  php:
    build:
      context: ./docker/php
    container_name: arpm-php-object-php
    environment:
      APP_ENV: dev
    volumes:
      - ./app/:/var/www/app
    ports:
      - '9000:9000'
    restart: always
    networks:
      - arpm-php-object-network

  nginx:
    image: nginx:stable-alpine
    container_name: arpm-php-object-nginx
    ports:
      - '80:80'
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    depends_on:
      - php
    restart: always
    networks:
      - arpm-php-object-network